
name: RSS Alerts Monitor

on:
  schedule:
    - cron: '0 0,7 * * *'   # 09:00 / 16:00 JST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run monitor
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          TZ: Asia/Tokyo
        run: |
          python monitor.py
          ls -la data || true

      - name: Commit & push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update RSS results [skip ci]" || echo "No changes"
          git push
